### ISSUE TITLE
assignment1

### ISSUE THREAD

**Issue by bigkat73** [aaaberg/Assignment-1#1]
# FEWD Week #1 Project: HTML/CSS Basics

---

### Description

For the first assignment, you will begin creating the beginnings of your first website. Take what you've learned from class and build a portfolio site that showcases all of the projects you'll be completing over the next few weeks. Build two pages - an 'About Page' and a 'Portfolio' - that link to one another. Your 'About Page' should describe your mission and value proposition and your 'Portfolio' should include descriptions of the work you [will] do for Relaxr, Startup Matchmaker, and CitiPix.

Student: ________________________________________

Project URL: ____________________________________

| Technical Requirements                                                                                                                                                        | Does Not Meet Expectations (0) | Meets Expectations (1) | Exceeds Expectations (2) |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------|------------------------|--------------------------|
| Link both pages together using `a` tag                                                                                                                                        |                                |                        |            2              |
| Use a unique `title` and a single unique `h1` tag                                                                                                                             |                                |                        |             2             |
| Show images using `img` tags including unique `alt` attributes                                                                                                                |                                |                        |              2            |
| Use an external CSS stylesheet to style your pages                                                                                                                            |                                |                        |            2              |
| Select at least 5 elements on the page and apply at least 5 different css properties (`font-size`, `color`, `font-family`, `background`, `text-decoration`) to these elements |                                |                        |            2              |
| Use at least 6 different HTML tags (`h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `p`, `ul`, `ol`, `a`, `img`) on your pages                                                            |                                |                        |              2            |
| Follow naming conventions, maintain consistency across your .html and .css files                                                                                              |                                |                        |            2              |
| Indent nested elements to increase your code's readability                                                                                                                    |                                |                        |              2            |
| TOTAL: __16____/16                                                                                                                                                              |                                |                        |                          |

Nice work here.  I really like how you personalized this.   I also like that you included the BEM naming convention here.   For certain things like paragraphs though I would stick with using the element selector p instead of adding classes to all the paragraphs just to save you time.

**Comment by aaaberg** [comment]
Thank you for your feedback, really appreciate it! Yeah, I agree it would've saved some time to stick with only styling the p selector. I wanted to get into the habit of styling it with a class, considering other pages could have different paragraph styling as the project grows. Also, I downloaded Emmet for Sublime and was able to only write p.paragraph to get the full tags - so that saved some time.
